file = open("demo.txt", "w")
file.write("Hello Aashish")
file.close()
file = open("demo.txt", "r")
print(file.read())
file.close()
file = open("demo.txt", "w")
file.write("Welcome to Python")
file.close()
file = open("demo.txt", "a")
file.write(" World")
file.close()
file = open("demo.txt", "r")
print(file.read()) 
file.close()
file = open("notes.txt", "w")
file.write("I am learning Python.")
file.close()
file = open("notes.txt", "r")
print(file.read())
file.close()
file = open("notes.txt", "a")
file.write("\nDay 21 completed.")
file.close()
name = input("Enter your name: ")
file = open("name.txt", "w")
file.write(name)
file.close()