age = int(input("Enter your age:"))
if age >= 18: print("Eligible for voting.")
else: print("Not eligible for voting.")
marks = int(input("Enter your marks:"))
if marks >= 90: print("Grade A")
elif marks >= 75: print("Grade B")
elif marks >= 50: print("Grade C")
else: print("Fail")
num = int(input("Enter your number:"))
if num%2 == 0: print("Even number.")
else: print("Odd number.")
age = int(input("Enter your age:"))
if age >= 60: print("You are senior citizen and can vote.")
elif age >= 18: print("You can vote.")
else: print("You are not eligible for voting.")
Password = int(input("Enter password:"))
if Password == 1234: print("Access granted.")
else: print("Wrong password.")
age = int(input("Enter your age:"))
Password = int(input("Enter password:"))
if age >= 18:
    if Password == 1234: print("Access granted.")
    else: print("Access denied")
else: print("underage")
